apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
    - name: nodejs-bharath
      image: arjunachari12/k8s-demo
      ports:
        - name: nodejsport
          containerPort: 3000
